"""
Curated book data for BookRecBot, organized by genre.

Each entry has: title, author, and a short original one-line summary
(written fresh for this bot, not copied from any publisher's blurb).
"""

BOOKS = {
    "fantasy": [
        {"title": "The Hobbit", "author": "J.R.R. Tolkien", "blurb": "A reluctant homebody is swept into a quest involving dwarves, a dragon, and a mysterious ring."},
        {"title": "A Wizard of Earthsea", "author": "Ursula K. Le Guin", "blurb": "A young mage's pride unleashes a shadow he must spend years learning to face."},
        {"title": "Mistborn: The Final Empire", "author": "Brandon Sanderson", "blurb": "A street thief with rare powers joins a plot to overthrow an immortal emperor."},
        {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "blurb": "A legendary figure recounts his rise from orphaned performer to feared magician."},
        {"title": "Circe", "author": "Madeline Miller", "blurb": "A minor witch from Greek myth is reimagined as the hero of her own long exile."},
        {"title": "The Lies of Locke Lamora", "author": "Scott Lynch", "blurb": "A con artist and his crew run elaborate schemes on the nobility of a canal city."},
        {"title": "Uprooted", "author": "Naomi Novik", "blurb": "A village girl is taken by a reclusive wizard to serve him, and finds more danger in the woods than in his tower."},
        {"title": "The Fifth Season", "author": "N.K. Jemisin", "blurb": "In a world of catastrophic quakes, people with the power to calm the earth are both feared and enslaved."},
    ],
    "science fiction": [
        {"title": "Dune", "author": "Frank Herbert", "blurb": "A noble family's heir is thrust into desert politics, prophecy, and a fight over a priceless resource."},
        {"title": "Ender's Game", "author": "Orson Scott Card", "blurb": "A gifted child is trained through brutal war games to lead humanity against an alien threat."},
        {"title": "The Left Hand of Darkness", "author": "Ursula K. Le Guin", "blurb": "An envoy on an icy planet navigates a society where gender is fluid and politics are treacherous."},
        {"title": "Project Hail Mary", "author": "Andy Weir", "blurb": "A lone astronaut wakes with no memory on a mission that may decide whether life on Earth survives."},
        {"title": "The Martian", "author": "Andy Weir", "blurb": "An astronaut stranded alone on Mars has to engineer his way to survival with what little he has."},
        {"title": "Snow Crash", "author": "Neal Stephenson", "blurb": "A hacker and a skateboard courier uncover a virus that spreads through both computers and minds."},
        {"title": "Children of Time", "author": "Adrian Tchaikovsky", "blurb": "A terraforming experiment goes sideways, giving rise to an unexpected new civilization."},
        {"title": "The Three-Body Problem", "author": "Liu Cixin", "blurb": "A scientist's discovery draws humanity into contact with a civilization facing its own crisis."},
    ],
    "mystery": [
        {"title": "The Murder of Roger Ackroyd", "author": "Agatha Christie", "blurb": "A famed detective is pulled into investigating the killing of a wealthy man in a quiet village."},
        {"title": "Gone Girl", "author": "Gillian Flynn", "blurb": "A wife's disappearance turns her husband into the prime suspect, and nothing about their marriage is as it seemed."},
        {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "blurb": "A disgraced journalist and a brilliant hacker dig into a decades-old disappearance."},
        {"title": "In the Woods", "author": "Tana French", "blurb": "A detective investigating a child's death must confront a case eerily similar to one from his own past."},
        {"title": "Big Little Lies", "author": "Liane Moriarty", "blurb": "A death at a school fundraiser unravels the secrets of three seemingly ordinary mothers."},
        {"title": "The Silent Patient", "author": "Alex Michaelides", "blurb": "A psychotherapist becomes obsessed with treating a woman who won't speak after her husband's murder."},
        {"title": "Sharp Objects", "author": "Gillian Flynn", "blurb": "A troubled reporter returns to her hometown to cover a murder and confronts her own dark past."},
        {"title": "The Thursday Murder Club", "author": "Richard Osman", "blurb": "Four retirees in a peaceful village turn their cold-case hobby into a real investigation."},
    ],
    "romance": [
        {"title": "Pride and Prejudice", "author": "Jane Austen", "blurb": "A sharp-witted young woman clashes with a proud, wealthy man whose first impression she can't shake."},
        {"title": "The Hating Game", "author": "Sally Thorne", "blurb": "Two rival coworkers locked in constant one-upmanship discover their animosity might be something else."},
        {"title": "Red, White & Royal Blue", "author": "Casey McQuiston", "blurb": "The son of the US President and a British prince go from public rivals to something far more complicated."},
        {"title": "Beach Read", "author": "Emily Henry", "blurb": "Two writers with opposite styles challenge each other to swap genres for the summer, and maybe fall for each other along the way."},
        {"title": "Outlander", "author": "Diana Gabaldon", "blurb": "A woman is swept back in time to 18th-century Scotland and torn between two lives and two loves."},
        {"title": "The Notebook", "author": "Nicholas Sparks", "blurb": "A story of a summer romance whose pull lasts decades, told through a notebook meant to bring back what was lost."},
        {"title": "It Ends with Us", "author": "Colleen Hoover", "blurb": "A woman's new relationship forces her to reckon with patterns from her childhood she swore she'd never repeat."},
        {"title": "People We Meet on Vacation", "author": "Emily Henry", "blurb": "Two best friends who take one trip together every year finally have to face what happened on their last one."},
    ],
    "thriller": [
        {"title": "The Girl on the Train", "author": "Paula Hawkins", "blurb": "A woman's daily train ride puts her at the center of a disappearance she may have witnessed."},
        {"title": "The Da Vinci Code", "author": "Dan Brown", "blurb": "A symbologist races across Europe following clues hidden in art and history after a murder at the Louvre."},
        {"title": "I Know What You Did Last Summer", "author": "Lois Duncan", "blurb": "A group of friends is stalked a year after covering up an accident together."},
        {"title": "The Silence of the Lambs", "author": "Thomas Harris", "blurb": "A young FBI trainee consults an imprisoned serial killer to catch one still active."},
        {"title": "Verity", "author": "Colleen Hoover", "blurb": "A struggling writer discovers disturbing secrets while finishing the unpublished work of an injured author."},
        {"title": "The Woman in the Window", "author": "A.J. Finn", "blurb": "An agoraphobic woman believes she's witnessed a crime in the house across the street, but no one believes her."},
        {"title": "Gone Baby Gone", "author": "Dennis Lehane", "blurb": "Two private investigators search for a missing child in a case that gets murkier the deeper they dig."},
        {"title": "The Reversal", "author": "Michael Connelly", "blurb": "A defense attorney is asked to prosecute a case for once, against a man he isn't sure is guilty."},
    ],
    "horror": [
        {"title": "The Haunting of Hill House", "author": "Shirley Jackson", "blurb": "Four strangers stay in a notoriously unsettling house to study its supposed supernatural activity."},
        {"title": "It", "author": "Stephen King", "blurb": "A group of childhood friends must face a shape-shifting evil that returns to their town decades later."},
        {"title": "Mexican Gothic", "author": "Silvia Moreno-Garcia", "blurb": "A woman visiting her cousin's new husband's remote estate senses something deeply wrong within its walls."},
        {"title": "The Shining", "author": "Stephen King", "blurb": "A family caretaking an isolated hotel for the winter is slowly consumed by the building's malevolent history."},
        {"title": "Bird Box", "author": "Josh Malerman", "blurb": "A mother navigates a world where seeing certain creatures drives people to violence, forcing her to travel blind."},
        {"title": "The Exorcist", "author": "William Peter Blatty", "blurb": "A mother seeks help from priests when her daughter's behavior turns increasingly disturbing."},
        {"title": "House of Leaves", "author": "Mark Z. Danielewski", "blurb": "A family's home turns out to be architecturally impossible, and a found manuscript tries to explain why."},
        {"title": "The Fisherman", "author": "John Langan", "blurb": "Two grieving widowers go fishing at a remote creek with a folklore-soaked history."},
    ],
    "historical fiction": [
        {"title": "All the Light We Cannot See", "author": "Anthony Doerr", "blurb": "A blind French girl and a German soldier's paths converge during the Second World War."},
        {"title": "The Book Thief", "author": "Markus Zusak", "blurb": "A young girl in Nazi Germany finds comfort in stolen books as the world around her falls apart."},
        {"title": "The Nightingale", "author": "Kristin Hannah", "blurb": "Two sisters in occupied France choose very different paths of resistance during the war."},
        {"title": "Wolf Hall", "author": "Hilary Mantel", "blurb": "A blacksmith's son rises to become one of the most powerful men in Henry VIII's court."},
        {"title": "The Pillars of the Earth", "author": "Ken Follett", "blurb": "The building of a cathedral in medieval England becomes the backdrop for decades of ambition and rivalry."},
        {"title": "Pachinko", "author": "Min Jin Lee", "blurb": "A Korean family's fortunes are followed across generations of hardship and change in Japan."},
        {"title": "The Guernsey Literary and Potato Peel Pie Society", "author": "Mary Ann Shaffer", "blurb": "A writer corresponds with residents of a Channel Island still processing life under wartime occupation."},
        {"title": "The Tattooist of Auschwitz", "author": "Heather Morris", "blurb": "A prisoner forced to tattoo fellow inmates finds an unlikely love within the camp."},
    ],
    "non-fiction": [
        {"title": "Sapiens", "author": "Yuval Noah Harari", "blurb": "A sweeping look at how Homo sapiens rose to dominate the planet, from foraging bands to global societies."},
        {"title": "Educated", "author": "Tara Westover", "blurb": "A woman raised off-grid with no formal schooling describes her path to a doctorate."},
        {"title": "The Immortal Life of Henrietta Lacks", "author": "Rebecca Skloot", "blurb": "The story behind cells taken without consent from a woman that became one of medicine's most important tools."},
        {"title": "Atomic Habits", "author": "James Clear", "blurb": "A practical breakdown of how small daily choices compound into major life changes."},
        {"title": "Quiet", "author": "Susan Cain", "blurb": "An exploration of introversion and the underrated strengths of people who prefer quieter environments."},
        {"title": "Into Thin Air", "author": "Jon Krakauer", "blurb": "A firsthand account of a disastrous Everest expedition and the decisions that led to tragedy."},
        {"title": "The Wright Brothers", "author": "David McCullough", "blurb": "A look at the two bicycle mechanics who solved the problem of powered human flight."},
        {"title": "Outliers", "author": "Malcolm Gladwell", "blurb": "A look at what actually separates extraordinary success stories from everyone else."},
    ],
    "biography": [
        {"title": "Steve Jobs", "author": "Walter Isaacson", "blurb": "A detailed account of the Apple co-founder's rise, downfall, and comeback, drawn from years of access."},
        {"title": "Alexander Hamilton", "author": "Ron Chernow", "blurb": "A comprehensive portrait of the founding father whose ideas still shape American government."},
        {"title": "Long Walk to Freedom", "author": "Nelson Mandela", "blurb": "Mandela's own account of his fight against apartheid and his 27 years in prison."},
        {"title": "The Diary of a Young Girl", "author": "Anne Frank", "blurb": "A teenager's diary written while hiding from Nazi persecution, later published by her surviving father."},
        {"title": "Becoming", "author": "Michelle Obama", "blurb": "The former First Lady traces her path from Chicago's South Side to the White House."},
        {"title": "Unbroken", "author": "Laura Hillenbrand", "blurb": "The story of an Olympic runner turned prisoner of war who survived extraordinary ordeals."},
        {"title": "Leonardo da Vinci", "author": "Walter Isaacson", "blurb": "A look at the relentless curiosity that connected da Vinci's art, science, and engineering."},
        {"title": "Just Mercy", "author": "Bryan Stevenson", "blurb": "A lawyer recounts his work defending wrongly condemned prisoners in the American South."},
    ],
    "self-help": [
        {"title": "Atomic Habits", "author": "James Clear", "blurb": "A practical breakdown of how small daily choices compound into major life changes."},
        {"title": "The 7 Habits of Highly Effective People", "author": "Stephen R. Covey", "blurb": "A framework for personal and professional effectiveness built on character rather than quick tricks."},
        {"title": "Mindset", "author": "Carol S. Dweck", "blurb": "Research on how believing abilities can grow, rather than being fixed, changes what people achieve."},
        {"title": "The Power of Now", "author": "Eckhart Tolle", "blurb": "A guide to reducing anxiety by shifting attention away from past and future and into the present moment."},
        {"title": "Man's Search for Meaning", "author": "Viktor E. Frankl", "blurb": "A psychiatrist's reflections on surviving the Holocaust and what gives life meaning even in suffering."},
        {"title": "Daring Greatly", "author": "Brené Brown", "blurb": "An argument that vulnerability, not armor, is what makes real courage and connection possible."},
        {"title": "The Subtle Art of Not Giving a F*ck", "author": "Mark Manson", "blurb": "A blunt take on choosing what actually deserves your energy instead of chasing constant positivity."},
        {"title": "Deep Work", "author": "Cal Newport", "blurb": "A case for protecting focused, distraction-free time as a rare and valuable skill."},
    ],
    "classic literature": [
        {"title": "1984", "author": "George Orwell", "blurb": "A man living under constant surveillance begins to question the totalitarian state that controls him."},
        {"title": "To Kill a Mockingbird", "author": "Harper Lee", "blurb": "A young girl watches her father defend a Black man falsely accused of a crime in the Depression-era South."},
        {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "blurb": "A mysterious millionaire's obsession with a lost love unravels amid the excess of the Jazz Age."},
        {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "blurb": "A destitute former student commits a murder and is consumed by guilt in its aftermath."},
        {"title": "Jane Eyre", "author": "Charlotte Brontë", "blurb": "An orphaned governess finds independence and love while confronting the secrets of her employer's house."},
        {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "blurb": "Generations of one family live through love, war, and strange fortune in a town touched by the fantastical."},
        {"title": "Brave New World", "author": "Aldous Huxley", "blurb": "A future society engineered for comfort and stability begins to unsettle one of its own citizens."},
        {"title": "Wuthering Heights", "author": "Emily Brontë", "blurb": "A turbulent, obsessive love story plays out across two families on the English moors."},
    ],
    "young adult": [
        {"title": "The Hunger Games", "author": "Suzanne Collins", "blurb": "A girl volunteers to fight to the death in a televised competition to save her sister."},
        {"title": "The Fault in Our Stars", "author": "John Green", "blurb": "Two teenagers with cancer fall in love while confronting mortality with dark humor and honesty."},
        {"title": "Percy Jackson & the Olympians: The Lightning Thief", "author": "Rick Riordan", "blurb": "A boy discovers he's the son of a Greek god and must prevent a war among the gods."},
        {"title": "The Perks of Being a Wallflower", "author": "Stephen Chbosky", "blurb": "A shy freshman navigates friendship, first love, and his own past through letters to a stranger."},
        {"title": "Divergent", "author": "Veronica Roth", "blurb": "In a society sorted by virtue, a girl who doesn't fit any category must hide what she really is."},
        {"title": "Eleanor & Park", "author": "Rainbow Rowell", "blurb": "Two misfit teens fall for each other over shared comic books and mixtapes on the school bus."},
        {"title": "The Book Thief", "author": "Markus Zusak", "blurb": "A young girl in Nazi Germany finds comfort in stolen books as the world around her falls apart."},
        {"title": "Six of Crows", "author": "Leigh Bardugo", "blurb": "A crew of talented criminals is recruited for a heist that could change the fate of their world."},
    ],
    "poetry": [
        {"title": "Milk and Honey", "author": "Rupi Kaur", "blurb": "A collection moving through pain, love, and healing in short, direct verses."},
        {"title": "Leaves of Grass", "author": "Walt Whitman", "blurb": "A sweeping celebration of individuality, nature, and the American spirit."},
        {"title": "Ariel", "author": "Sylvia Plath", "blurb": "A raw, intense final collection exploring identity, motherhood, and despair."},
        {"title": "The Sun and Her Flowers", "author": "Rupi Kaur", "blurb": "A follow-up collection tracing growth from wilting to blooming through loss and self-discovery."},
        {"title": "Selected Poems", "author": "Mary Oliver", "blurb": "Quiet, observant poems rooted in nature and attention to the everyday world."},
        {"title": "Where the Sidewalk Ends", "author": "Shel Silverstein", "blurb": "Playful, imaginative poems for readers of any age, mixing humor with quiet insight."},
        {"title": "The Complete Poems", "author": "Emily Dickinson", "blurb": "Compact, unconventional poems on death, nature, and the inner life, mostly unpublished in her lifetime."},
        {"title": "Citizen: An American Lyric", "author": "Claudia Rankine", "blurb": "A blend of poetry and prose examining race and everyday life in America."},
    ],
    "adventure": [
        {"title": "Treasure Island", "author": "Robert Louis Stevenson", "blurb": "A young boy's discovery of a map sets him on a voyage after buried pirate treasure."},
        {"title": "Life of Pi", "author": "Yann Martel", "blurb": "A shipwrecked teenager shares a lifeboat with a Bengal tiger on a months-long survival journey."},
        {"title": "The Call of the Wild", "author": "Jack London", "blurb": "A domesticated dog is thrust into the harsh wilderness of the Yukon during the gold rush."},
        {"title": "Into the Wild", "author": "Jon Krakauer", "blurb": "The true story of a young man who left civilization behind to live alone in the Alaskan wilderness."},
        {"title": "Robinson Crusoe", "author": "Daniel Defoe", "blurb": "A shipwrecked sailor spends decades surviving alone on a remote island."},
        {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "blurb": "An aging fisherman battles a giant marlin far out at sea in a test of endurance and pride."},
        {"title": "King Solomon's Mines", "author": "H. Rider Haggard", "blurb": "An expedition sets out across Africa in search of a legendary lost treasure."},
        {"title": "The Sign of the Four", "author": "Arthur Conan Doyle", "blurb": "Sherlock Holmes investigates a case involving stolen treasure and a decades-old betrayal."},
    ],
    "comedy": [
        {"title": "Good Omens", "author": "Terry Pratchett and Neil Gaiman", "blurb": "An angel and a demon team up to stop the apocalypse, mostly because they've grown fond of Earth."},
        {"title": "The Hitchhiker's Guide to the Galaxy", "author": "Douglas Adams", "blurb": "An ordinary Englishman is swept into space moments before Earth is casually demolished."},
        {"title": "Bridget Jones's Diary", "author": "Helen Fielding", "blurb": "A single woman in London chronicles her chaotic year of resolutions, romance, and self-deprecating humor."},
        {"title": "Where'd You Go, Bernadette", "author": "Maria Semple", "blurb": "A teenager pieces together clues to find her eccentric, disappeared architect mother."},
        {"title": "Bossypants", "author": "Tina Fey", "blurb": "A comedic memoir covering Fey's rise through improv, Saturday Night Live, and beyond."},
        {"title": "Furiously Happy", "author": "Jenny Lawson", "blurb": "A memoir that finds absurd humor in living with mental illness and chronic anxiety."},
        {"title": "The Rosie Project", "author": "Graeme Simsion", "blurb": "A socially awkward geneticist runs a systematic search for the perfect partner, with messy results."},
        {"title": "Confessions of a Shopaholic", "author": "Sophie Kinsella", "blurb": "A financial journalist can give anyone money advice except herself."},
    ],
}

GENRE_LABELS = {
    "fantasy": "Fantasy",
    "science fiction": "Science Fiction",
    "mystery": "Mystery",
    "romance": "Romance",
    "thriller": "Thriller",
    "horror": "Horror",
    "historical fiction": "Historical Fiction",
    "non-fiction": "Non-Fiction",
    "biography": "Biography",
    "self-help": "Self-Help",
    "classic literature": "Classic Literature",
    "young adult": "Young Adult",
    "poetry": "Poetry",
    "adventure": "Adventure",
    "comedy": "Comedy",
}

# Aliases so users can type natural variations
GENRE_ALIASES = {
    "sci-fi": "science fiction",
    "scifi": "science fiction",
    "sci fi": "science fiction",
    "ya": "young adult",
    "self help": "self-help",
    "selfhelp": "self-help",
    "nonfiction": "non-fiction",
    "non fiction": "non-fiction",
    "classic": "classic literature",
    "classics": "classic literature",
    "funny": "comedy",
    "humor": "comedy",
    "humour": "comedy",
}


def normalize_genre(text: str) -> str:
    key = text.strip().lower()
    key = GENRE_ALIASES.get(key, key)
    return key
